import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Lang = "es" | "va";

interface LangState {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const DICT: Record<Lang, Record<string, string>> = {
  es: {
    "app.tagline": "🌊 Aventura submarina",
    "app.title": "¡Descubre el<br />Oceanogràfic!",
    "app.intro": "Una misión interactiva por el acuario más grande de Europa.",
    "app.meta": "<strong>6 actividades</strong> · ⏱️ ~40 minutos",
    "app.namePrompt": "¿Cuál es tu nombre, explorador/a?",
    "app.namePh": "Escribe aquí tu nombre",
    "app.start": "🚀 ¡Empezar la aventura!",
    "app.nameError": "Escribe tu nombre (al menos 2 letras)",
    "app.source": "Información basada en",
    "lang.label": "Idioma",
    "hub.hello": "Hola,",
    "hub.activities": "actividades",
    "hub.intro": "Elige una actividad para empezar. Puedes hacerlas en el orden que quieras.",
    "hub.results": "🏆 Ver mis resultados",
    "hub.restart": "🔄 Empezar de nuevo",
    "header.map": "Mapa",
    "header.explorer": "Explorador",
    "act.quiz.title": "Cuestionario",
    "act.quiz.desc": "8 preguntas de opción múltiple",
    "act.vf.title": "Verdadero o Falso",
    "act.vf.desc": "8 afirmaciones marinas",
    "act.parejas.title": "Une los conceptos",
    "act.parejas.desc": "Empareja animales con su zona",
    "act.mapa.title": "Mapa interactivo",
    "act.mapa.desc": "Explora las 9 zonas del acuario",
    "act.sopa.title": "Sopa de letras",
    "act.sopa.desc": "Encuentra 8 animales marinos",
    "act.ordenar.title": "Cadena alimentaria",
    "act.ordenar.desc": "Ordena del más pequeño al mayor",
    "common.completed": "¡Completado!",
    "common.youGot": "Has acertado",
    "common.of": "de",
    "common.back": "Volver al mapa",
    "common.question": "Pregunta",
    "common.next": "Siguiente →",
    "common.finish": "Terminar",
    "common.continue": "Continuar →",
    "common.correct": "¡Correcto! 🐠",
    "common.almost": "¡Casi! Sigue intentando 🐡",
    "vf.true": "✓ Verdadero",
    "vf.false": "✗ Falso",
    "vf.was": "Era",
    "vf.TRUE": "VERDADERO",
    "vf.FALSE": "FALSO",
    "vf.ok": "¡Correcto! 🌟",
    "parejas.intro": "Toca un animal y luego su <strong>zona del Oceanogràfic</strong>. Errores:",
    "parejas.animals": "🐠 Animales",
    "parejas.zones": "🌊 Zonas",
    "parejas.allDone": "🎉 ¡Todas emparejadas!",
    "parejas.errors": "Errores",
    "parejas.hits": "Aciertos",
    "mapa.intro": "Haz clic en cada <strong>zona del Oceanogràfic</strong> y responde su pregunta.",
    "mapa.finish": "🏁 Terminar —",
    "mapa.hits": "aciertos",
    "sopa.intro": "Arrastra para seleccionar las palabras (horizontal, vertical o diagonal). Encontradas:",
    "sopa.toFind": "A buscar:",
    "sopa.done": "🏁 ¡Terminado!",
    "sopa.skip": "Saltar",
    "ordenar.intro": "Ordena de <strong>presa</strong> (abajo de la cadena) a <strong>gran depredador</strong> (arriba).<br />Usa las flechas ▲▼ para colocar cada animal.",
    "ordenar.check": "✓ Comprobar",
    "ordenar.perfect": "🎉 ¡Perfecto!",
    "ordenar.inPlace": "en su sitio",
    "res.diploma": "Diploma de",
    "res.given": "Otorgado a",
    "res.score": "Puntuación total",
    "res.foot": "Aventura en el Oceanogràfic de Valencia · 6º Primaria",
    "res.back": "← Volver al mapa",
    "res.new": "🔄 Nueva aventura",
    "res.t1": "Maestro/a del Oceanogràfic",
    "res.m1": "¡Increíble! Conoces el océano como nadie.",
    "res.t2": "Explorador/a marino/a",
    "res.m2": "¡Genial! Has demostrado mucho conocimiento.",
    "res.t3": "Buceador/a curioso/a",
    "res.m3": "¡Buen trabajo! Aún hay más por descubrir.",
    "res.t4": "Pez aventurero",
    "res.m4": "Sigue practicando, ¡puedes mejorar!",
    "res.t5": "Aprendiz del océano",
    "res.m5": "¡Sigue explorando para descubrir más!",
  },
  va: {
    "app.tagline": "🌊 Aventura submarina",
    "app.title": "Descobreix l'<br />Oceanogràfic!",
    "app.intro": "Una missió interactiva per l'aquari més gran d'Europa.",
    "app.meta": "<strong>6 activitats</strong> · ⏱️ ~40 minuts",
    "app.namePrompt": "Quin és el teu nom, explorador/a?",
    "app.namePh": "Escriu ací el teu nom",
    "app.start": "🚀 Comença l'aventura!",
    "app.nameError": "Escriu el teu nom (almenys 2 lletres)",
    "app.source": "Informació basada en",
    "lang.label": "Idioma",
    "hub.hello": "Hola,",
    "hub.activities": "activitats",
    "hub.intro": "Tria una activitat per començar. Pots fer-les en l'ordre que vulgues.",
    "hub.results": "🏆 Veure els meus resultats",
    "hub.restart": "🔄 Començar de nou",
    "header.map": "Mapa",
    "header.explorer": "Explorador",
    "act.quiz.title": "Qüestionari",
    "act.quiz.desc": "8 preguntes d'opció múltiple",
    "act.vf.title": "Vertader o Fals",
    "act.vf.desc": "8 afirmacions marines",
    "act.parejas.title": "Uneix els conceptes",
    "act.parejas.desc": "Aparella animals amb la seua zona",
    "act.mapa.title": "Mapa interactiu",
    "act.mapa.desc": "Explora les 9 zones de l'aquari",
    "act.sopa.title": "Sopa de lletres",
    "act.sopa.desc": "Troba 8 animals marins",
    "act.ordenar.title": "Cadena alimentària",
    "act.ordenar.desc": "Ordena del més xicotet al més gran",
    "common.completed": "Completat!",
    "common.youGot": "Has encertat",
    "common.of": "de",
    "common.back": "Tornar al mapa",
    "common.question": "Pregunta",
    "common.next": "Següent →",
    "common.finish": "Acabar",
    "common.continue": "Continuar →",
    "common.correct": "Correcte! 🐠",
    "common.almost": "Quasi! Continua intentant-ho 🐡",
    "vf.true": "✓ Vertader",
    "vf.false": "✗ Fals",
    "vf.was": "Era",
    "vf.TRUE": "VERTADER",
    "vf.FALSE": "FALS",
    "vf.ok": "Correcte! 🌟",
    "parejas.intro": "Toca un animal i després la seua <strong>zona de l'Oceanogràfic</strong>. Errors:",
    "parejas.animals": "🐠 Animals",
    "parejas.zones": "🌊 Zones",
    "parejas.allDone": "🎉 Totes aparellades!",
    "parejas.errors": "Errors",
    "parejas.hits": "Encerts",
    "mapa.intro": "Fes clic en cada <strong>zona de l'Oceanogràfic</strong> i respon la seua pregunta.",
    "mapa.finish": "🏁 Acabar —",
    "mapa.hits": "encerts",
    "sopa.intro": "Arrossega per seleccionar les paraules (horitzontal, vertical o diagonal). Trobades:",
    "sopa.toFind": "A buscar:",
    "sopa.done": "🏁 Acabat!",
    "sopa.skip": "Saltar",
    "ordenar.intro": "Ordena de <strong>presa</strong> (baix de la cadena) a <strong>gran depredador</strong> (dalt).<br />Usa les fletxes ▲▼ per col·locar cada animal.",
    "ordenar.check": "✓ Comprovar",
    "ordenar.perfect": "🎉 Perfecte!",
    "ordenar.inPlace": "al seu lloc",
    "res.diploma": "Diploma de",
    "res.given": "Atorgat a",
    "res.score": "Puntuació total",
    "res.foot": "Aventura a l'Oceanogràfic de València · 6é Primària",
    "res.back": "← Tornar al mapa",
    "res.new": "🔄 Nova aventura",
    "res.t1": "Mestre/a de l'Oceanogràfic",
    "res.m1": "Increïble! Coneixes l'oceà com ningú.",
    "res.t2": "Explorador/a marí/ina",
    "res.m2": "Genial! Has demostrat molt coneixement.",
    "res.t3": "Bussejador/a curiós/osa",
    "res.m3": "Bon treball! Encara hi ha més per descobrir.",
    "res.t4": "Peix aventurer",
    "res.m4": "Continua practicant, pots millorar!",
    "res.t5": "Aprenent de l'oceà",
    "res.m5": "Continua explorant per descobrir més!",
  },
};

const Ctx = createContext<LangState | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("es");
  const setLang = useCallback((l: Lang) => setLangState(l), []);
  const t = useCallback((key: string) => DICT[lang][key] ?? key, [lang]);
  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>;
}

export function useLang() {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
